version: '2'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
#      DATABASE_URL: mysql2://root:root@mysql:3306
    ports:
      - 3000:3000
    volumes:
      - .:/var/app
#  mysql:
#    image: mysql:5.7
#    environment:
#      MYSQL_ROOT_PASSWORD: 'root'
#    ports:
#      - 23306:3306
#    volumes:
#      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
