version: 2
jobs:
  build:
    working_directory: /var/app
    docker:
      - image: debian:jessie

    environment:
      TEST_REPORTS: /tmp/test-reports
      TEST_RESULTS: /tmp/test-results
      DOCKER_VER: 17.03.0-ce

    steps:
      - checkout
      
#      - run: mkdir -p $TEST_RESULTS

      - setup_remote_docker

      # This should go into custom primary image, here's only for the sake of explanation
      - run: apt-get update && apt-get install -y \
          curl \
          --no-install-recommends && rm -rf /var/lib/apt/lists/*
      - run:
          name: Install Docker client
          command: |
            set -x
            curl -L -o /tmp/docker-$DOCKER_VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$DOCKER_VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
#      - run:
#          name: Build service
#          command: make

      - run:
          name: Start container and verify it's working
          command: docker-compose up -d

      - run: docker-compose run app bundle install
      - run: docker-compose run app bundle exec rake test
